name: Build Validation

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Check PR title with Commitizen
        if: github.event_name == 'pull_request'
        run: |
          poetry run cz check --message "${{ github.event.pull_request.title }}" || 
          (echo "Invalid PR title! Use Conventional Commit format (e.g., 'feat: add X')" && exit 1)

      - uses: ./.github/workflows/lint-and-test.yml
        with:
          python-version: ${{ matrix.python-version }}
