name: Publish Package to PyPI

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Publish Package to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/refcheck/
    permissions:
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y
          poetry config virtualenvs.create false

      - name: Install Dependencies
        run: poetry install --sync --no-interaction

      - name: Build
        run: poetry build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.13.0
